{% set name = "astpretty" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a801fcda604ec741f010bb36d7cbadc3ec8a182ea6fb83e20ab663463e75ff6

build:
  number: 0
  noarch: python
  entry_points:
    - astpretty = astpretty:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - astpretty
  commands:
    - pip check
    - astpretty --help
  requires:
    - pip

about:
  home: https://github.com/asottile/astpretty
  summary: Pretty print the output of python stdlib `ast.parse`.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
